### ISSUE TITLE
worksheet.to_df() not outputting columns with duplicated lnames.

### ISSUE THREAD

**Issue by ChristopherYJS** [originlab/originpro#1]
to_df not outputting columns with duplicated lnames.
it overwrites the column instead.
#[265ebb1](https://github.com/sylvanace/originpro/tree/patch-1)

**Comment by pawchen** [comment]
The package is not developed in this repo, I informed the developers internally and they will take a look at this issue. Thank you for your time and effort submitting the issue and the potential fix.
