### ISSUE TITLE
FutureWarning: iteritems is deprecated

### ISSUE THREAD

**Issue by stefan-wak** [originlab/originpro#2]
Importing data from a pandasDF i got this error (in Origin 2021 and 2023)
```
C:\ProgramData\OriginLab\100\PyPackage\Py3\originpro\worksheet.py:255: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for key, value in df.iteritems():
```
After changing the line to ```for key, value in df.items():``` everything works fine without errors.

**Comment by pawchen** [comment]
@folger Could you please take a look at this issue?

**Comment by pawchen** [comment]
I got the message from the internal team that this issue is fixed. Closing.
