### ISSUE TITLE
How to change font type and how to reverse the axis

### ISSUE THREAD

**Issue by Wuchilpaba** [originlab/originpro#3]
Hello,
         I have wrote a Python script to deal with my own data, but i need to change the font type in the whole graph, such as the X axis, Y axis and the title of the graph. Besides, how to reverse the axis, the problem has puzzled me a lot. Hope I can get a proper method to figure out.

Sincerely yours,
Sheng-Ye

**Comment by pawchen** [comment]
Hello,

Please note that this repository is not monitored by our tech support colleges. Please use our forum (https://my.originlab.com/forum/) for discussions. For urgent request please use either the "Submit a Support Ticket" button or the online chat option over our official website: https://www.originlab.com/index.aspx?go=COMPANY/ContactUS.

Thanks!

**Comment by Wuchilpaba** [comment]
Thanks! I have opened a new topic in the forum.

Sincerely yours,
Sheng-Ye
